### ISSUE TITLE
Periodic Test Failure

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2156]
```
Failures:

  1) ManifestBuilder#build when it is a Playlist with proxies to FileSets generates the Canvases for the FileSets
     Failure/Error: expect(first_canvas["label"]["@none"]).to eq ["Proxy Title"]
     
       expected: ["Proxy Title"]
            got: ["Proxy Title2"]
     
       (compared using ==)
     # ./spec/services/manifest_builder_spec.rb:217:in `block (5 levels) in <top (required)>'
     # ./spec/support/with_queue_adapter.rb:7:in `block in with_queue_adapter'
     # ./spec/support/with_queue_adapter.rb:7:in `block in with_queue_adapter'
```

Doesn't seem to be attached to a specific seed. Probably some sort of odd ordering issue.
